### ISSUE TITLE
Unclear sort order

### ISSUE THREAD

**Issue by Quantumplation** [TestStack/TestStack.Dossier#16]
Hello again!

It is unclear to me in what order the .With lambdas are applied...

For example, I have
```
public static class Depots.SomeObj
{
    public static IListBuilder<SomeObjBuilder> RandomList(int n)
    {
        return CreateListOfSize(n)
          .All()
             .With(x => x.SomeCustomization("RandomDefault"));
    }
}
```
and then 
```
var listBuilder = Depots.SomeObj.RandomList(10)
    .All()
        .With(x => x.SomeCustomization("Override"));
```

and the order they are executed is difficult to quantify.  It seems the first time listBuilder.Build() is called, it executes Override and then RandomDefault, but the second time, it's the other way around.

**Comment by robdmoore** [comment]
That code is all NBuilder code. Off the top of my head I'm surprised by what you are describing though.

I don't see a call to random in there so I assume your issue is different to https://github.com/garethdown44/nbuilder/issues/25?

FYI I'm removing NBuilder from NTestDataBuilder v2 in favour of a much nicer syntax. Feel free to check out the v2 PR for details. You can try out the v2 latest via the NuGet feed on my CI server: http://ci.robdmoore.id.au:8010/guestAuth/app/nuget/v1/FeedService.svc/

**Comment by Quantumplation** [comment]
Yes, it's different from the issue you linked.  Tomorrow, when I'm at work, I'll get you an explicit code sample that's causing the issue.

I'll check out V2 later tonight, I'm excited!

**Comment by robdmoore** [comment]
Reach out if you need help, but the BREAKING_CHANGES file in that branch describes the main changes anyway.

**Comment by robdmoore** [comment]
I suspect this should not be the case anymore with v2. Feel free to re-open if it is though.
