### ISSUE TITLE
Consider splitting the Any functionality into a separate library

### ISSUE THREAD

**Issue by michael-wolfenden** [TestStack/TestStack.Dossier#30]
I think the Any functionality is awesome and can think of a number of scenario's outside of Dossier where it could be used.

Would you consider separating it into its own library, perhaps TestStack.Any?

**Comment by robdmoore** [comment]
Hi Michael,

Is there a reason why you can use it by including TestStack.Dossier? There isn't much extra weight on top of the Any stuff in Dossier (NSubstitute as a dependency and a couple of extra classes). The way I see it the Any stuff is as much a first class citizen as the TestDataBuilder stuff is (that isn't really reflected in the documentation yet though).

I'm not completely adverse to pulling it out to a separate library, but just not sure if there is a point since it's easy to use it separately now :)

If we did pull it out another name idea would be TestStack.Anon.

Thoughts @mwhelan @MehdiK @JakeGinnivan?

**Comment by michael-wolfenden** [comment]
Rob,

Not concerned about the weight, thinking more from a separation of concerns perspective. I've been doing a bunch of loading testing and setting up sample data.I think the ability to create anonymous data would be of great benefit to the community. Like you say, you think of it as a first class citizan so why not treat it as such?

It just thought it would be cool to import a package and start using `Any.PositiveInteger()` without creating a new `AnonymousValueFixture`. I was also thinking of adding all the field types from mockaroo.

**Comment by robdmoore** [comment]
Fair enough.

Being able to use Any.Whatever from anywhere is tricky because it removes the ability to add your own extension methods (unless you can think of a way to achieve both?).

In terms of separation of concerns you could look at it both ways - both parts of Dossier is about generating test data ;) If there are a few people that agree that it makes sense to separate out I'm more than happy to.

**Comment by michael-wolfenden** [comment]
hmmm..just about the get on a plane so this might nor be fully thought out, but you could have a custom object hanging off Any ie. Any.Custom that people can attach their extension methods to, so Any.Custom.MySpecficMethod.

Either way, its you call.. Thanks for you responses and consideration.. I will close this issue out.
