### ISSUE TITLE
Can I turn off the anonymous values generation for a builder?

### ISSUE THREAD

**Issue by cottsak** [TestStack/TestStack.Dossier#53]

**Comment by robdmoore** [comment]
You can register value supplier that returns what you expect or set explicit default values in the builder ctor

**Comment by cottsak** [comment]
I am setting explicit values in the builder ctor however it seems other members with public setters are getting anon values and those values are potentially upsetting my tests. So I want to turn that off.

**Comment by robdmoore** [comment]
Override the build method and call the ctor of the object yourself?

**Comment by cottsak** [comment]
There is no ctor of the object being built - it's a dto, usually constructed with `{ ... }`. I tried using the build method override but it seems the anon values are still being inserted. So there isn't a first class way to disable this behaviour I guess?

**Comment by robdmoore** [comment]
By default it uses the `PublicPropertySettersFactory` (https://github.com/TestStack/TestStack.Dossier/blob/master/TestStack.Dossier/TestDataBuilder.cs#L79).

This ensures `Get` is called for every property with a public setter and that automatically supplies an anonymous value if you haven't set an explicit one: https://github.com/TestStack/TestStack.Dossier/blob/master/TestStack.Dossier/TestDataBuilder.cs#L162.

What you could do is create a `PublicPropertySettersWithDefaultValueFactory` that calls `GetOrDefault` rather than `Get` and then override `BuildObject` to use that to construct the object?

**Comment by cottsak** [comment]
That's painful.. especially since to get what I want with the DTOs is essentially a simple ctor invoke. Looks like less code to write simple builder types without the foo of `TestDataBuilder`. That's a pity.

I can see the thought behind "let's dump random stuff into a given type" but that's potentially not a state a lot of legacy code is going to like, mine included. I don't think that behaviour should be enabled by default. Perhaps you should opt in if you want the `PublicPropertySettersFactory`-rando-magic.

**Comment by robdmoore** [comment]
I'm more than happy to take a pull request that allows the default to be changed.

To be honest I expect most people to overload BuildObject anyway, it's only the most simple scenarios that automatic object creation works.

I think it's entirely reasonable that people need to extend that method and take control of object construction - it's not a huge amount of work to do that once for each object being built.

You then still get all the advantages that the library provides around removing noise from builders and terse, powerful and extensible value generation.

Obviously, if that's stuff you don't need then don't use the library :)

**Comment by cottsak** [comment]
You should know me by now Rob, if my pain exceeds the threshold there will be a PR, I promise. 😃 

Thanks for your help.

**Comment by KostaMadorsky** [comment]
@robdmoore I wonder if anything changed since 2016.
Are there any ways to use default values if property was not Set on the builder?

Your suggestion to create a custom Factory and use GetOrDefault can be tricky to implement since GetOrDefault does not have an overload that accepts property type and name and Has method is protected.
