### ISSUE TITLE
Question about usage scenarios

### ISSUE THREAD

**Issue by TehWardy** [TestStack/TestStack.Dossier#54]
Hi Guys,

I'm just trying to setup some generic testing code that will have nbuilder construct objects, send them to an API and then pull them back to confirm that the API saved them right.

From the documentation on the homepage I could only really figure out that this library is just a more wordy / code heavy version of manually constructing the object and setting all the values or just using nbuilder directly.

I would like someone to help me understand the benefit of this package if possible so I don't miss an opportunity whilst constructing a test framework. 

Can someone tell me how this improves our testing experience over the base nbuilder lib?

**Comment by robdmoore** [comment]
Compared to NBuilder there are three advantages:

1) if you are building domain objects without public property setters then it's set up to allow you to do that properly by creating builder classes tersely that ensure you don't break domain invariants and you describe the axioms that can happen in your domain (thus forming a sort of documentation)
2) if you are building pocos with public setters then you can use Builder<T> rather than creating a builder class for each object (e.g. the same terseness as NBuilder), but you have much terser list building syntax since you can avoid the .With(b => ...). See the documentation for creating lists to see what I mean.
3) there is very powerful features for you to control automatic anonymous value generation both automatically when something is built as well as explicitly via the AnonymousValueFixture class (usually exposed via a variable called Any).

**Comment by TehWardy** [comment]
Hmm ok ...

 1) I'm not (so probably doesn't apply i'm guessing)
 2) Yeh this is what I am currently doing using the base NBuilder package
         - Unless I missed something here?
 3) Are these extended beyond the base set that NBuilder gives us in some meaningful way?
         - I guess I can figure that myself by digging through the code here

 Thanks for the feedback.

**Comment by robdmoore** [comment]
For 2 I was referring to http://dossier.teststack.net/docs/creating-lists, although if you aren't building explicit builder classes then that syntax would look the same as NBuilder.

For 3 I'd say look at http://dossier.teststack.net/docs/anonymous-values-and-equivalence-classes to see if the functionality in dossier is useful to you :)

**Comment by TehWardy** [comment]
Thx rob
