### ISSUE TITLE
Simple bool Get() is failing to return default(bool) (aka False)

### ISSUE THREAD

**Issue by cottsak** [TestStack/TestStack.Dossier#61]
Take a look at this example project: https://www.dropbox.com/s/l4m8l92uyvwc6co/RepoBuilderBoolDefaultValBug.zip?dl=0

There is a failing test in there but actually it should be passing. I have no idea why this is broke but it is.

**Comment by robdmoore** [comment]
That's by design :)

When you Get a value it generates an anonymous value as per http://dossier.teststack.net/docs/anonymous-values-and-equivalence-classes.

If you want the default value to be returned for the type if it's not set then use `GetOrDefault` rather than `Get`.

**Comment by cottsak** [comment]
@robdmoore This is extremely unsettling. I don't know how a user would find this the implicit behavior. I would expect most folks to be surprised (like me) when they discover the default value for the type is not the default from `Get`. It's not intention revealing and forced me to log an issue, when TBH, I wasn't going to search doco for something which didn't present as anything other than a bug.

**Comment by robdmoore** [comment]
The anonymous value support is a very important part of Dossier - it allows you to make your builders even terser by negating the need to define `Set` calls in the ctor for most builders. It also allows you to make use of the equivalence class pattern and comes into it's own when building lists of objects since they all come out with different values.

**Comment by cottsak** [comment]
Perhaps it's because I don't often use those other features, I can't appreciate their needs in influencing this behavior.
